### ISSUE TITLE
total variation of cp4.2 in java instead of matlab

### ISSUE THREAD

**Issue by probinso** [GaloisInc/ppaml-cp4#11]
the email thread with subject heading **RE: CP4 file output format** mentions a file that is provided in matlab.

Because we haven't required the teams in the past to have matlab running on their machines, we should provide this in a non-proprietary language. (Java has been mentioned)

**Comment by ssorower** [comment]
Hi Philip,
IIRC, in the past we decided that as long as the Matlab codes are Octave compatible, we are good. In this particular case, this Matlab code runs on Octave - I just double checked on "GNU Octave, version 3.4.3". 
So, I believe on the "non-proprietary language" argument, we are good. 
Matlab is good at loading/processing large matrices - that's the only reason I chose Matlab here. That said, if there really is a necessity for a Java version, then sure, I can spend some time to get that done.

**Comment by cscherrer** [comment]
Brian Ruttenberg's suggestion:

> Let me just comment on this from a performers point of view. I was under the impression (and please correct if I am wrong), that Galois would like to run our code and generate the metric files. In CP4.1, the TVD computation is done in java, so I can just call that computation directly and output it after running the model. Since the CP4.2 computation is in Matlab, I have to call out to Matlab/Octave in our solution to compute the TVD. This is not a great solution since you get into issues of paths, filesystems, etc, and just because it works on my machine doesn't mean it will work for Galois when they run it.

> Can I propose an alternative solution? The posterior marginals for each disease and each case are almost always nearly one or zero. Meaning the posterior joint over the 20 diseases is basically zero for all but a handful of the 2^20 configurations. Can I just sample from the posterior joint, and use the TVD computation from CP4.1 to just compute a sample-to-sample TVD? It would be very easy to just sample the ground truth posteriors you gave us, and I doubt there would be any perceptible difference in TVD given the low entropy of the distributions.

**Comment by bruttenberg** [comment]
I'd like to add that the same thing can be done for problem 3 (sampling the ground truth).

**Comment by ssorower** [comment]
(1) it seems for now it will be easy for me to just re-implement the Matlab scripts (CP4.2 and CP4.3) in Java. 

(2) I think your alternate solution proposal is about right. Tom and I talked about this approach but then decided to use the true posterior since we have them readily available. 

If we decide to use the TVD computation from CP4.1 for problems 4.2 and 4.3, then either we'll have to provide samples from the true posterior (instead of the true posterior probabilities that we currently provide), or will have to ask you (and other teams) to generate n samples from the given true posterior - and then compute the required metric using the TVD code given for CP4.1.

This is doable but we'll have to see if Tom has any other point. He is out of town so we may not hear from him until next week.

**Comment by bruttenberg** [comment]
Ok, thanks for the update. There’s not really a rush on this, so I’m sure next week is fine.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by ssorower** [comment]
I have the Java/jar files ready that can replace the Matlab codes for CP4.2 and CP4.3. We'll be uploading them soon - we'll also have to add the command line instruction in the solution documents.

**Comment by ssorower** [comment]
The JAR files for CP4.2 and 4.3 has been uploaded. We have also updated the solution documents to include the instructions on how to run these JAR files.
