### ISSUE TITLE
challenge problem 4.3 - Question about numerical representation in csv files

### ISSUE THREAD

**Issue by probinso** [GaloisInc/ppaml-cp4#8]
It looks like `problem-3-true-state.csv` is a (0,1)-adjacency-matrix and `problem-3-outputs.csv` contains an adjacentcy-list. I expect that these files should have the same formatting as eachother.

It looks like a csv with headers for both of these files would be simpler.
```
time   state
```

**Comment by ssorower** [comment]
Hi Philip

These two files have different information – one has the ground truth states at each time step (problem-3-true-state.csv) and the other has the observations at each time step (problem-3-outputs.csv). Obviously we cannot use the same headers for both of these files. Also, “time” here does not necessarily mean time in clock.

The true-state CSV is written like an adjacency matrix (more like a probability matrix I’d say) because the teams will also learn probabilities for each of these cells. And the observation CSV just says what was observed at each time step.

I don’t see any reason to change these files at all – these are pretty standard.
We could convert the true-state CSV to write like observation CSV, The observation CSV (problem-3-outputs.csv) will have headers: time, observation; and The true-state CSV (problem-3-true-state.csv) will have headers: time, state. But I don't know if that will change anything, or be useful at all.

Thanks,
--Shahed

**Comment by cscherrer** [comment]
It was surprising to me that the formats are different. Since the true state and the observed state are both realized (as opposed to a latent value from some distribution), it makes more sense to me to represent them in the same format. So I had assumed the inconsistency was just from a minor oversight. The format you ( @ssorower ) describe in your last paragraph above is exactly what I would expect.

It's certainly usable either way. If you strongly prefers the current format, it's probably not worth the time to debate, and we should leave it as is.

**Comment by cscherrer** [comment]
Leaving as is, since zero/one matrix is interpreted as probabilities.
