### ISSUE TITLE
challenge problem 4.8 - evaluation data is missing

### ISSUE THREAD

**Issue by probinso** [GaloisInc/ppaml-cp4#9]
There is public facing data that the teams can use to test and verify their results, however when we run/evaluate their submissions we would like to use a dataset they haven't seen before. This is to deter the teams from producing over-fitting submissions.

Is this available?

**Comment by nimar** [comment]
Hi Philip,

I was not aware of this requirement. We can certainly generate yet 
another data set. However, if we haven't already released the data set 
then we could simply remove the labeled ground truth data.

:-) Nim

**Comment by slater-ppaml** [comment]
Hi Nim,

We should generate another data set solely for evaluation (and keep this 
data private).

Michael

**Comment by nimar** [comment]
Hi Michael,

Generating the data is trivial. However, we would have to make a number 
of changes to the documentation to explain the purpose of this new data 
set. Note: we already have two data sets -- the short data and the large 
data. A third data set would cause a lot of confusion.

Now, if we haven't released the data set then simply removing the 
test.data file would achieve the same objective with very little 
disruption. There is already a test.blind file in the data set so that 
is all that the teams need.

Actually, even if we have released the data set we could simply generate 
a brand new data set without the test.data file and push it out as a 
replacement data.

:-) Nim

**Comment by slater-ppaml** [comment]
Hi Nim,

The documentation doesn't need any changes. The additional data is for 
the evaluation Galois performs of the solutions that the teams submit. 
In other words, we want the teams to have everything they need to 
develop solutions, but we want to evaluate the solutions on different data.

Generating a brand new data set as you described would be perfect.

Cheers,
Michael

**Comment by nimar** [comment]
OK, I will upload a new directory call eval_data which you will publish 
to the competitors sans the physics.data and the test.data files, and 
somehow the teams will know that they have to submit a test.data file 
for this data set??

I'm clearly missing some piece of the puzzle here.

:-) Nim

**Comment by tdietterich** [comment]
My understanding is that Galois will rerun the submitted code on this test data.

--Tom

--
Thomas G. Dietterich, Distinguished Professor Voice: 541-737-5559
School of Electrical Engineering              FAX: 541-737-1300
  and Computer Science                        URL: eecs.oregonstate.edu/~tgd
US Mail: 1148 Kelley Engineering Center
Office: 2067 Kelley Engineering Center
Oregon State Univ., Corvallis, OR 97331-5501

**Comment by nimar** [comment]
Ah, I get it now. I didn't realize that the teams were submitting their 
code as well.

:-) Nim

**Comment by nimar** [comment]
Directory eval_data uploaded to owncloud with 100 training and test 
episodes. This contains a sample solution as well.

:-) Nim

**Comment by probinso** [comment]
Neato!

and Thanks :)
